# Generated by Django 3.2.12 on 2024-02-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
    ]
