# Generated by Django 3.2.12 on 2024-02-09 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=12, max_digits=4)),
                ('image', models.ImageField(upload_to='images/')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='templates.size')),
            ],
        ),
    ]
