# Generated by Django 5.0.2 on 2024-02-18 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0002_remove_pizza_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("complete", models.BooleanField(default=False)),
                ("delivery", models.BooleanField(default=True)),
                ("items", models.ManyToManyField(to="templates.pizza")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
