# Generated by Django 5.0.2 on 2024-02-18 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0003_basket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basket",
            old_name="id",
            new_name="basket_id",
        ),
    ]
