# Generated by Django 5.0.2 on 2024-02-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0004_rename_id_basket_basket_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="image",
            field=models.ImageField(
                default="images/999-piz-create-your-own.webp", upload_to="images/"
            ),
        ),
    ]
