# Generated by Django 5.0.2 on 2024-02-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0009_pizza_sauce_alter_pizza_crust"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="toppings",
            field=models.ManyToManyField(blank=True, to="templates.topping"),
        ),
    ]
