# Generated by Django 5.0.2 on 2024-02-21 15:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0010_alter_pizza_toppings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="size",
            field=models.ForeignKey(
                blank=True,
                default="2",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="templates.size",
            ),
        ),
        migrations.CreateModel(
            name="PizzaUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_ordered", models.DateTimeField(auto_now_add=True)),
                ("full_name", models.CharField(max_length=200)),
                (
                    "card_number",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Card number must be 16 digits long",
                                regex="^\\d{16}$",
                            )
                        ],
                    ),
                ),
                (
                    "cvv",
                    models.CharField(
                        max_length=4,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                3, "CVV must be at least 3 digits long"
                            ),
                            django.core.validators.MaxLengthValidator(
                                4, "CVV must be no more than 4 digits long"
                            ),
                        ],
                    ),
                ),
                (
                    "expiry_date",
                    models.CharField(
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Expiry date must be in MM/YY format",
                                regex="^(0[1-9]|1[0-2])\\/\\d{2}$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField()),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="templates.basket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
