# Generated by Django 3.2.12 on 2024-02-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0011_alter_pizza_size_pizzauser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='images/create-your-own.webp', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pizzauser',
            name='address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pizzauser',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='pizzauser',
            name='cvv',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='pizzauser',
            name='expiry_date',
            field=models.CharField(max_length=5),
        ),
    ]
