# Generated by Django 3.2.12 on 2024-02-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0012_auto_20240222_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
